---
title: "Capstone 1"
subtitle: "Pronósticos Simples"
author: "**Universidad del Norte** Eco 1731: Econometría II"
date: "<br> **Fecha Límite**: viernes, 7 marzo 2025"
output: 
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      ratio: '8.5:11'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: clear

```{R, setup, include = F}
# Packages
library(pacman)
p_load(
  ggplot2, gridExtra, ggthemes, latex2exp, kableExtra,
  tidyverse, broom, knitr, magrittr
)
# Colors
red_pink <- "#e64173"
turquoise <- "#20B2AA"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
# Themes
theme_axes_y <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.y = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_x <- theme_void() + theme(
  text = element_text(family = "sans"),
  axis.title = element_text(size = 11),
  plot.title = element_text(size = 11, hjust = 0.5),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, -0.2, 0, 0, unit = "lines")),
  axis.text.x = element_text(
    size = 10, angle = 0, hjust = 0.9, vjust = 0.5,
    margin = margin(0, 0.4, 0, 0, unit = "lines")
  ),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.07, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 11))
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  warning = F,
  message = F
)
```

.mono[**ENTREGABLE**]: El proyecto debe ser realizado máximo por cuatro (4) personas. Para las **siguientes** preguntas conteste solo lo que se le pide. **No se acepta** ningún trabajo adicional a la fecha del _viernes 7 _ del mes de marzo hasta la hora de las 23:59 en la carpeta del brightspace disponible para esto y cuya entrega solo debe hacerla un/a (1) de los integrantes del grupo.

Las entregas debe hacerlas en la [Carpeta Capstone](https://cursos.uninorte.edu.co/d2l/home/125748) respectiva. **Sus entregas pueden ser de dos archivos**: (.hi[1]) Uno donde van los análisis que puede ser un documento pdf con nomnre (_p.e._, .hi[yanesmolaramos.pdf]) y en otro archivo (.hi[2]) el script de .mono[R]. Otra alternativa -que es mejor aún- es hacerlo mediante un (.hi[1]) solo archivo tipo **Markdown** donde incluye automáticamente el script y las respuestas del taller.

.mono[**OBJETIVO**]: Esto tiene tres intenciones: (1) re-forzar lo visto en clases; (2) Usted aprenda a preparar un informe con las herramientas de .mono[R];  y  ademas (3) ver que tan hábil es para resolver problemas con series de tiempo.

## Problema 1: Análisis de Tendencia

**1a.** Tome los datos de la base del Banrep desde el link: [Series Económicas](https://suameca.banrep.gov.co/estadisticas-economicas/#/home) y escoja un item cualquiera con 30 datos (mensuales o trimestrales) y realice un análisis completo, incluyendo un reporte de estadísticas básicas para la serie que ha elegido.

**1b.** Construya un histograma de frecuencias para la serie. ¿Qué le indica?

**1c.** Establezca un análisis del componente de la serie (Tendencia). ¿ Cuál es la dinámica de la serie en el periodo de estudio?

**1d.** ¿Cuál de los tipos de tendencia básicos se ajusta mejor dentro del análisis de los anteriores componentes? y ¿En que se basa su apreciación?

**1e.** Desestacionalice la serie y establezca un comparativo entre la original y la desestacionalizada.


## Problema 2: Media y Varianza

Sea los siguientes procesos:

| F(x) | 0.20 | 0.19 | 0.18 | 0.05 | 0.02 | 0.36 |
|------|------|------|------|------|------|------|
| X    | 24   | -11  | 8    | 4    | -5   | -1   |

| F(y) | 0.29 | 0.18 | 0.09 | 0.19 | 0.15 | 0.10 |
|------|------|------|------|------|------|------|
| Y    | 4.3  | 5.2  | -1.2 | 1.4  | 4.2  | 5.3  |


**2a.** Establezca el valor esperado o media $E(X)$ y $E(Y)$, ademas de la varianza $var(X)$ y $var(Y)$ para cada una de las anteriores series.

**2b.** Para las siguientes ecuaciones encuentre la media y la varianza (hagalo de forma manual) y luego opcional en .mono[R]:

- $Y_{t}=1+0.35Y_{t-1}+\epsilon_{t}$ donde $\epsilon_{t} \sim (0, 0.4)$.  
- $Y_{t}=1+0.93Y_{t-1}+\epsilon_{t}$ donde $\epsilon_{t} \sim (0, 3)$.

---
class: clear

## Problema 3: Aprenda de Máxima verosimilitud

**3a.** Plantee la función de máxima verosimilitud en términos logarítmicos y halle el parámetro (estimador) de $(\beta_{0})$ de la función:
$$\mathcal{L} \left ( \mu \right )=  \frac{1}{\left (2\pi\sigma^{2}\right )^{n/2}}  exp \left \{ -\frac{1}{2\sigma^{2}} \sum \limits_{i=1}^{n} \left ( y_{i}-\beta_{0}-\beta_{1}x_{i} \right )^{2} \right \}$$
**3b.** Cuál viene a ser el resultado del parámetro de $\beta_{1}$? (demuestrelo y explique cada paso de la ecuación)

## Problema 4: Empalme

Tome una serie anual (puede ser del DANE) que tenga dos periodos de referencia. Por ejemplo PIB a precios constantes de 2005 y otro con PIB a precios constantes del 2018 y empalmelas de tal manera que se conviertan en una sola serie de tiempo en una misma base de año <br/>

**4.a** Muestre las graficas de ambas series

**4.b** Demuestre que logran empalmar en un perido adecuado. Diga en que periodo lo logra o consigue.

## Problema 5: Su serie

En conformidad con cada grupo de trabajo las series que vayan a presentar deben:

**5.a** Establecer una descripción de la serie de tiempo y mencionar la motivación que lo/a llevó a elegir dicha serie.

**5.b** Hacer una descomposición de la serie a partir de lo estacional. Muestre los gráficos de eso.

**5.c** Si por tendencia se tratara intente de retirarle la tendencia. Qué ocurre con su serie? plantee su gráfico respectivo

**5.d** Halle la predicción de los próximos 3 periodos a acontecer. Aplique las técnicas de media móvil, Box-Cox, Holt-winters y finalmente ETS. *Cuál predice mejor?* (Puede crear una tabla y hacer comparativos).



